car/urls.py
from django.urls import path
from . import views

app_name = 'car'

urlpatterns = [


]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('post.urls'),name='post'),
    path('food/', include('food.urls'),name='food'),
# path('', include('food.urls'),name='food'),
    path('car/', include('car.urls'),name='car'),


]

food/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'food'


urlpatterns = [
    path('pizza/',views.show_pizza,name='pizza'),
    path('berenjmorgh/',views.berenjmorgh,name='berenjmorgh'),
    path('hamburger',views.hamburger,name='hamburger'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'


urlpatterns = [


   path('', views.show_post, name='show'),

]

car/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.

class Post(models.Model):

    STATUS_CHOICES = (

        ('Published', 'Published'),
        ('Unpublished', 'Unpublished'),
        ('draft', 'Draft'),
        ('confirmed', 'Confirmed'),

    )

    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='Published')


    def __str__(self):

        return self.status

car/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader


# Create your views here.
def show_pizza(request):
  return render(request, 'food/pizza.html')


def berenjmorgh(request):
  return render(request, 'food/berenjmorg.html')

def hamburger(request):
  return render(request, 'food/hamburger.html')

post/views.py
from django.db.models.signals import post_save
from django.shortcuts import render
from post.models import Post


# Create your views here.
def show_post(request):
    posts=Post.objects.all()

    # only filters status='Published'
    # posts=Post.objects.filter(status='Published')


    return render(request,'show_post.html',{'posts':posts})

food/templates/food/berenjmorg.html
{% extends '_base.html'%}

{% block title %}

BERENJMORGH PAGE
{% endblock title%}

 {% block content %}
<div class="container col-12 align-center margin-auto  justify-content-center justify-align-center breadcrumb_part container-md">

  <h1 class="text-danger h1 display-1 text-center">THE BODY CONTENT OF BERENJMORGH PAGE</h1>

</div>

{% endblock content %}

food/templates/food/hamburger.html
{% extends '_base.html'%}

{% block title %}

HAMBURGER PAGE
{% endblock title%}

 {% block content %}


<div class="container">

 <h1>THE BODY CONTENT OF HAMBURGER PAGE</h1>

</div>


{% endblock content %}

food/templates/food/pizza.html
{% extends '_base.html'%}

{% block title %}

PIZZA PAGE
{% endblock title%}

 {% block content %}

     <h3>

  <small class="text-muted display-1">THE BODY CONTENT OF PIZZA PAGE</small>
</h3>



{% endblock content %}

post/templates/show_post.html
{% extends '_base.html' %}

{% block title %}
	Show_post
{% endblock title%}


{% block content %}
	  <h1 class="display-1">Display 1 Display 1Display 1Display 1Display 1Display 1Display 1Display 1Display 1</h1>
{% endblock content %}

templates/_base.html
<!doctype html>
<html  lang="fa" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>
        {% block title %}

    {% endblock title %}
    </title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/navbar.html
 <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">

                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'food:pizza' %}">صفحه اصلی</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'food:pizza' %}">پیتزا</a>
                                </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'food:berenjmorgh' %}">همبرگر</a>
                                </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'food:hamburger' %}">برنج مرغ</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        انواع غذاها
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" href="product_list.html"> لیست محصولات</a>
                                        <a class="dropdown-item" href="single-product.html">جزئیات محصول</a>

                                    </div>
                                </li>


                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_2"
                                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        وبلاگ
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                        <a class="dropdown-item" href="blog.html">درباره رستوران</a>
                                        <a class="dropdown-item" href="single-blog.html">صفحه داخلی وبلاگ</a>
                                    </div>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="contact.html">تماس با ما</a>
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <a href="cart.html">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">

        </div>
    </header>

templates/show_post.html
{#{% extends "admin/base_site.html" %}#}
{% extends '_base.html' %}

{% block title %}
	Show_post
{% endblock title%}


{% block content %}


           <h1 class="display-1 text-center">Show Post 5</h1>
           <hr>



                      {% for post in posts %}
                       <h1 class="display-1">{{ post.title }}</h1>
                       <p>{{ post.content }}</p>
                       <h3>{{ post.status }}</h3>
                       <p>تاریخ ایجاد: {{ post.created_at }}</p>
                     {% endfor %}



               <p>==================================================</p>








{% endblock content %}